### ISSUE TITLE
[Feedback] Conan Essentials - Transitive CMake Integration advice

### ISSUE THREAD

**Issue by Minimonium** [conan-io/training#28]
The course showcases how to use `cmake_find_package` generator, but it doesn't quite mention that for the moment Conan doesn't quite get the Components right, which would be an immediate question of a listener who sees the Boost being linked as Boost::Boost.

I'm not sure if it's appropriate for the Essentials course, but maybe a small note somewhere that mentions it could help a bit. Or not.

**Comment by solvingj** [comment]
We probably won't take any action on this because, while unfortunate at the moment, eventually boost/components will work (hopefully very soon). I don't want to clutter the lesson with a note about temporary bug. With that said, you have a point and it's not a trivial thing... just not something we have time to tweak (there's so much left to do :()
