### ISSUE TITLE
Conan Advanced - Exercise 16: zlib build failed

### ISSUE THREAD

**Issue by gikari** [conan-io/training#34]
When trying to run the last command from the exercise (`conan create . user/testing -pr=rpi_armv7 --build=missing`), the unintended error is displayed:

```
ERROR: 404: Not Found. [Remote: conan-center]
The 'zlib/1.2.11' package has 'exports_sources' but sources not found in local cache.
Probably it was installed from a remote that is no longer available.
```

**Comment by memsharded** [comment]
Hi @gikari 

Can you please post here the output of your ``conan remote list``?

I would say that you did the Essentials training first, and you did the ``conan remote remove conan-center`` that is explained not to remove. Adding it later will not recover the association of the zlib that is in the cache with the remote.

You could try:

```
$ conan remove "zlib*" -f
```
That will force a fresh installation from the conan-center. Please let us know how it goes.

**Comment by gikari** [comment]
> 
> Can you please post here the output of your `conan remote list`?
> 

```
conan-center: https://conan.bintray.com [Verify SSL: True]
artifactory: https://genda.jfrog.io/artifactory/api/conan/conan [Verify SSL: True]
```
The last one is my custom remote from one of the Essentials exercises.

> 
> You could try:
> 
> ```
> $ conan remove "zlib*" -f
> ```
> 
> That will force a fresh installation from the conan-center. Please let us know how it goes.

This helped, thanks! Not sure why this error happened, what I did is only the commands from the exercises of the Essentials course.

**Comment by memsharded** [comment]
Happy to hear that it worked!

> his helped, thanks! Not sure why this error happened, what I did is only the commands from the exercises of the Essentials course.

Yes, I would bet that you ran the command ``conan remote remove conan-center`` in one of the slides in the Essentials training, that is commented out and explained that this could be done if you wanted to disconnect, but tells to NOT run it. The effect of running this is that you remove the ConanCenter in the known remotes. This is why trying to build ``zlib`` package locally didn't work, because it was missing the some sources, but as the remote was removed, it didn't know how to get those files.

I think this issue can be closed now, but don't hesitate to open a new one if you have any further question!
