### ISSUE TITLE
getting an error when preparing the environment for doing the exercises

### ISSUE THREAD

**Issue by ruksan** [conan-io/training#50]
I am on windows 10.
while doing the training on
https://academy.jfrog.com/path/conan/conan-essentials/590849#

I get the below error when running the third command below to prepare the environmet
 git clone https://github.com/conan-io/training
cd training/docker_environment
docker-compose up -d  ===========> This an error
docker exec -it conan-training bash

The error I get is

Step 9/10 : ENV DEMO_ART_CREDS_PSW=password
 ---> Using cache
 ---> 3591c351707e
Step 10/10 : RUN /scripts/bootstrap-artifactory-config.sh
 ---> Running in 659b99e05aea
/bin/sh: 1: /scripts/bootstrap-artifactory-config.sh: not found
Service 'artifactory-training' failed to build : The command '/bin/sh -c /scripts/bootstrap-artifactory-config.sh' returned a non-zero code: 127

Can someone please help on how to proceed.
Thanks

**Comment by gprosch** [comment]
I am on Win 10 and also getting the same result as ruksan.

**Comment by solvingj** [comment]
@gprosch or @ruksan can you please let us know if pulling the latest update allows you to get past this error?

**Comment by ruksan** [comment]
Hi, Good day.
Thanks a lot for looking into this and the quick response.
I am still getting the same error even after pulling the latest changes.
Can you please check.
I am on windows 10 and trying these commands using Git Bash. 

Thanks

**Comment by ruksan** [comment]
@gprosch 
  Did you try pulling the latest repo ?
Thanks

**Comment by solvingj** [comment]
Please try deleting and re-pulling the scripts for.

**Comment by memsharded** [comment]
It might help also:

- Making sure to stop instances: ``docker-compose down``
- Clearing old images, container, networks: ``docker image ls -a``, ``docker container ls -a`` to list, then ``docker container rm xxx``, etc. A ``docker system prune -a`` will completely remove all containers and images (use with caution, it removes everything!)
- Pulling the latest changes
- ``docker-compose up -d`` (re-build from scratch)

**Comment by uilianries** [comment]
After the latest change, it's working for me.

**Comment by solvingj** [comment]
to force rebuild from scratch and then re-start, you'll need to do:
`docker-compose build --no-cache && docker-compose up -d`

**Comment by ruksan** [comment]
I did all above and even restarted my machine and tried.
But no luck. I get the same error

**Comment by solvingj** [comment]
I believe I know what the issue is. 
By default, Git for windows automatically replaces UNIX new line characters with Windows new line characters.
This causes a problem when docker copies those scripts into the Linux container and tries to run them.  They have windows new line characters, and therefor linux fails to run them. 

There are a few ways to solve this problem. 

First, I will now work on a solution which fixes the new line characters after they are copied into the container so that this issue never happens to anyone again. 

Second, for users who might want to fix the issue themselves right now.  This command should do the trick:

`sed -i "s/\r//g" docker_environment/artifactory-training/scripts/*.sh`

Please let me know if you try this command, otherwise, we'll submit the PR to fix the issue permanently ASAP.

**Comment by solvingj** [comment]
@gprosch @ruksan i have submitted a PR to fix the issue regardless of the git-for-windows setting. Please try again with the latest.

**Comment by gprosch** [comment]
I have very little experience with Docker but I get the impression that maybe I should be going into some kind of Docker container to execute the command?

 

I don’t have sed since I am on Windows but I did try running the sed command via Docker.  That didn’t work so I downloaded a gnuwin version of sed and rant the command you gave.  It didn’t make an changes to the files that my diff utility (Beyond Compare) could detect.

 

 

Greg

**Comment by solvingj** [comment]
Good try @gprosch . I implemented the fix in the PR so you should not have to run any commands now.  You should just be able to pull the latest changes and run the following command:

`docker-compose build --no-cache && docker-compose up`

This should re-build the `jfrog-artifactory-training` from scratch (because of the `--no-cache`) and then start up the new build.

**Comment by ruksan** [comment]
Thanks all. It works for me now

**Comment by gprosch** [comment]
It's working for me now.  Thank you!
